apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: {{ template "fullname" . }}
    spec:
      containers:
      - env:
        - name: CONNECT_URL
          value: "http://kafka-connect-kafka-connect.default.svc.cluster.local:8083"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ template "name" . }}
        ports:
        - containerPort: {{ .Values.service.connectui.port }}
        - containerPort: {{ .Values.service.fastdatadev.port }}
        resources: {}
      restartPolicy: Always
status: {}
