apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ template "oracle.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: {{ template "oracle.fullname" . }}
    spec:
      containers:
      - env:
        - name: ORACLE_SID
          value: EE
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ template "oracle.name" . }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources: {}
      restartPolicy: Always
status: {}
