apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ template "oracle.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: {{ template "oracle.fullname" . }}
    spec:
      containers:
      - env:
        - name: ORACLE_SID
          value: ORADB
        - name: ORACLE_ALLOW_REMOTE
          value: "true"
        - name: ORACLE_DISABLE_ASYNCH_IO
          value: "false"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ template "oracle.name" . }}
        command: ["/bin/sh", "-c"]
        args:
            - >-
              apt-get update -y;
              apt-get install git-core -y;
              git clone https://github.com/vmware/tungsten-replicator.git;
              chmod +x ./replicator/extractors/oracle-cdc/setupCDC.sh;
              ./replicator/extractors/oracle-cdc/setupCDC.sh;
              /usr/local/bin/docker-entrypoint;
        ports:
        - containerPort: {{ .Values.service.port }}
        resources: {}
      restartPolicy: Always
status: {}
