apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: {{ template "oracle.name" . }}
  name: {{ template "oracle.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "{{ .Values.service.port }}"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    name: {{ template "oracle.name" . }}
