apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.project }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ .Values.pdName }}
    fsType: ext4
