apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ksql.fullname" . }}
  labels:
    app: {{ template "ksql.name" . }}
    chart: {{ template "ksql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ksql.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ksql.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command:
          #- sh
          #- -c
          #- |
          #  ksql-server-start /etc/ksql/ksqlserver1.properties > /tmp/ksql-logs/ksql-server.log 2>&1 &
          args:
            - perl
            - -e
            - while(1){ sleep 99999 }
          env:
            - name: KSQL_CONFIG_DIR
              value: /etc/ksql
            - name: KSQL_LOG4J_OPTS
              value: -Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties
            - name: STREAMS_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.host }}:{{ .Values.kafka.port }}
            - name: STREAMS_SCHEMA_REGISTRY_HOST
              value: {{ .Values.schemaRegistry.host }}
            - name: STREAMS_SCHEMA_REGISTRY_PORT
              value: "{{ .Values.schemaRegistry.port }}"
          ports:
            - name: headless
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: config
            mountPath: /etc/ksql/ksqlserver1.properties
            readOnly: true
            subPath: ksqlserver1.properties
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ template "ksql.name" . }}-configmap
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
