apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    
  creationTimestamp: null
  labels:
    
  name: {{ template "ksql.fullname" . }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: {{ template "ksql.fullname" . }}
    spec:
      containers:
      - args:
        - perl
        - -e
        - while(1){ sleep 99999 }
        env:
        - name: KSQL_CONFIG_DIR
          value: /etc/ksql
        - name: KSQL_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties
        - name: STREAMS_BOOTSTRAP_SERVERS
          value: kafka:29092
        - name: STREAMS_SCHEMA_REGISTRY_HOST
          value: schema-registry
        - name: STREAMS_SCHEMA_REGISTRY_PORT
          value: "8081"
        image: confluentinc/ksql-cli:0.5-rc0
        name: ksql-cli
        resources: {}
      restartPolicy: Always
status: {}
