apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f /home/avigershon/projects/ksql/docs/quickstart/docker-compose.yml
      convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: schema-registry
  name: schema-registry
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: schema-registry
status:
  loadBalancer: {}
