apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f /home/avigershon/projects/ksql/docs/quickstart/docker-compose.yml
      convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  ports:
  - name: "32181"
    port: 32181
    targetPort: 32181
  selector:
    io.kompose.service: zookeeper
status:
  loadBalancer: {}
