apiVersion: v1
kind: Service
metadata:
  name: {{ template "ksql-server.fullname" . }}
  labels:
    app: {{ template "ksql-server.name" . }}
    chart: {{ template "ksql-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  #clusterIP: "{{ .Values.service.clusterIP }}"
  
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: headless
  selector:
    app: {{ template "ksql-server.name" . }}
    release: {{ .Release.Name }}
status:
  loadBalancer: {}
