apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: {{ template "fullname" . }}
    spec:
      containers:
      - env:
        - name: ID
          value: "01"
        - name: HOST
          value: "landoop-fast-data-connect-cluster.default.svc.cluster.local"
        - name: BS
          value: "kafka-kafka.default.svc.cluster.local:9092"
        - name: ZK
          value: "kafka-zookeeper.default.svc.cluster.local:2181"
        - name: SR
          value: "http://schema-registry-schema-registry.default.svc.cluster.local:8081"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ template "name" . }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources: {}
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
      - env:
        - name: CONNECT_URL
          value: "http://localhost:8083"
        - name: PROXY
          value: "false"
        image: "landoop/kafka-connect-ui:latest"
        name: {{ template "name" . }}-ui
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
      volumes:
        - name: google-cloud-key
          secret:
            secretName: bq-key
status: {}
