apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: {{ template "elasticsearch.name" . }}
  name: {{ template "elasticsearch.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "{{ .Values.service.port }}"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    name: {{ template "elasticsearch.name" . }}
