apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "blackbird.fullname" . }}
  labels:
    app: {{ template "blackbird.name" . }}
    chart: {{ template "blackbird.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "blackbird.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "blackbird.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - sh
          - -c
          - |
            /blackbird/start_blackbird.sh
          #args:
          #  - perl
          #  - -e
          #  - while(1){ sleep 99999 }
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: config
            mountPath: /blackbird/blackbird.config
            readOnly: true
            subPath: blackbird.config
        - name: filebeat
          image: "{{ .Values.filebeat.image.repository }}:{{ .Values.filebeat.image.tag }}"
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          env:
          - name: ELASTICSEARCH_HOST
            value: {{ .Values.filebeat.output.host }}
          - name: ELASTICSEARCH_PORT
            value: "{{ .Values.filebeat.output.port }}"
          - name: ELASTICSEARCH_USERNAME
            value: elastic
          - name: ELASTICSEARCH_PASSWORD
            value: changeme
          - name: ELASTIC_CLOUD_ID
            value:
          - name: ELASTIC_CLOUD_AUTH
            value:
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
          - name: config
            mountPath: /etc/filebeat.yml
            readOnly: true
            subPath: filebeat.yml
          - name: prospectors
            mountPath: /usr/share/filebeat/prospectors.d
            readOnly: true
          - name: data
            mountPath: /usr/share/filebeat/data
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0444
          name: {{ template "blackbird.name" . }}-configmap
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
