apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "blackbird.fullname" . }}
  labels:
    app: {{ template "blackbird.name" . }}
    chart: {{ template "blackbird.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "blackbird.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "blackbird.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - sh
          - -c
          - |
            /blackbird/start_blackbird.sh
          #args:
          #  - perl
          #  - -e
          #  - while(1){ sleep 99999 }
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: data
            mountPath: /blackbird
          - name: config
            mountPath: /blackbird/blackbird.config
            readOnly: true
            subPath: blackbird.config
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          defaultMode: 0444
          name: {{ template "blackbird.name" . }}-configmap
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
