apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  settings.js: |-
    module.exports = {
      editorTheme: {
         projects: {
             enabled: false
         }
      },
      credentialSecret: "lioran020",
      uiPort: process.env.PORT || 1880,
      mqttReconnectTime: 15000,
      serialReconnectTime: 15000,
      debugMaxLength: 1000,
      functionGlobalContext: {
        puppeteer:require('puppeteer')
      }
    }
