apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "name" . }}
spec:
  serviceName: {{ template "name" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      updateStrategy:
        type: RollingUpdate
        containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["npm", "start", "--", "--userDir", "/data", "--settings", "/usr/src/node-red/node_modules/node-red/settings/settings.js"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              name: {{ template "name" . }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          volumeMounts:
          - mountPath: /data
            name: {{ template "name" . }}-data
          - mountPath: /usr/src/node-red/node_modules/node-red/settings
            name: {{ template "name" . }}-settings
          resources:
{{ toYaml .Values.resources | indent 12 }}
      restartPolicy: Always
      volumes:
      - name: {{ template "name" . }}-settings
        configMap:
          name: {{ template "name" . }}-configmap
          items:
          - key: settings.js
            path: settings.js
      - name: {{ template "name" . }}-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "name" . }}-data
      {{- else }}
        emptyDir: {}
      {{ end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
