apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "filebeat.name" . }}-config
  namespace: kube-system
  labels:
    k8s-app: {{ template "filebeat.name" . }}
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    filebeat.config:
      prospectors:
        # Mounted `filebeat-prospectors` configmap:
        path: ${path.config}/prospectors.d/*.yml
        # Reload prospectors configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "filebeat.name" . }}-prospectors
  namespace: kube-system
  labels:
    k8s-app: {{ template "filebeat.name" . }}
    kubernetes.io/cluster-service: "true"
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "filebeat.name" . }}
  namespace: kube-system
  labels:
    k8s-app: {{ template "filebeat.name" . }}
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: {{ template "filebeat.name" . }}
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: {{ template "filebeat.name" . }}
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ template "filebeat.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: {{ .Values.output.host }}.{{if ne .Values.namespace "default"}}{{ .Values.namespace }}{{end}}
        - name: ELASTICSEARCH_PORT
          value: "{{ .Values.output.port }}"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        - name: ELASTIC_CLOUD_ID
          value:
        - name: ELASTIC_CLOUD_AUTH
          value:
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: prospectors
          mountPath: /usr/share/filebeat/prospectors.d
          readOnly: true
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ template "filebeat.name" . }}-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: prospectors
        configMap:
          defaultMode: 0600
          name: filebeat-prospectors
      - name: data
        emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "filebeat.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "filebeat.name" . }}
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "filebeat.name" . }}
  labels:
    k8s-app: {{ template "filebeat.name" . }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "filebeat.name" . }}
  namespace: kube-system
  labels:
    k8s-app: {{ template "filebeat.name" . }}
